import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>NOG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>NOG</h1> {/* capital and thin letters */}
        <Link href="login">
          <span>Log In</span>
        </Link> 
        <Link href="signup">
          <span>Sign Up</span>
        </Link>
      </header>
      <main>
        <section>
          <h1>Hero</h1>
          <h1>NOG</h1>
          <h2>Organised Gaming</h2>
        </section>
        <section>
          <h1>Features</h1>
          <h2>Schedule Game Nights</h2>
          <h2>Make Adjustments Easily</h2>
          <h2>Discord Integration</h2>
        </section>
        <section>
          <h1>CTA</h1>
          <Link href="signup">
            <h1>Join Today</h1>
          </Link>
        </section>
        <footer>
          <h1>Made by Fenroe</h1>
        </footer>
      </main>
    </>
  )
}
