import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>NoG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>NOG</h1> {/* capital and thin letters */} 
        <span>Sign In</span>
      </header>
      <main>
        <section>
          <h1>Hero</h1>
        </section>
        <section>
          <h1>Features</h1>
        </section>
        <section>
          <h1>CTA</h1>
        </section>
        <footer>
          <h1>Made by Fenroe</h1>
        </footer>
      </main>
    </>
  )
}
